version: '3'

services:
  mysql:
    image: mysql:8.3.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: test_db
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
  dockerize:
    image: jwilder/dockerize:0.6.0
    profiles:
      - dockerize
volumes:
  db-store:
